### ISSUE TITLE
Support dev mode

### ISSUE THREAD

**Issue by alansemenov** [enonic/cli-enonic#460]
```[tasklist]
### Tasks
- [ ] https://github.com/enonic/cli-enonic/issues/463
- [x] Add `dev` task to `build.gradle` of all our starters so that it doesn't fail when CLI tries to run "`./gradlew dev`". This `dev` task should execute continuous deploy, except for starters where we support watch mode (see below).
- [x] "`dev`" task in Tsup Starter should run the app in watch mode (`npm run watch`).
- [ ] https://github.com/enonic/starter-tsup/issues/233
- [ ] https://github.com/enonic/cli-enonic/issues/470
- [ ] https://github.com/enonic/cli-enonic/issues/471
- [ ] https://github.com/enonic/cli-enonic/issues/472
```
